services:
  site:
    build: .
    ports:
      - "4321:4321"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.stb-middleware.replacepathregex.regex=^/$"
      - "traefik.http.middlewares.stb-middleware.replacepathregex.replacement=/$${1}"
      - "traefik.http.routers.stb-site.rule=Host(`simply-the.best`)"
      - "traefik.http.routers.stb-site.service=site-service"
      - "traefik.http.routers.stb.rule=HostRegexp(`[a-z0-9-]+\\.simply-the\\.best`)"
      - "traefik.http.routers.stb.service=site-service"
      - "traefik.http.routers.stb.middlewares=stb-middleware"
      - "traefik.http.services.site-service.loadbalancer.server.port=4321"
